export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';

export const GET_DIR_TREE = 'GET_DIR_TREE';
export const GET_DIR_TREE_FULFILLED = 'GET_DIR_TREE_FULFILLED';
export const GET_DIR_TREE_REJECTED = 'GET_DIR_TREE_REJECTED';