export const POST_FILE = 'IMPORT';
export const POST_FILE_FULFILLED = 'POST_FILE_FULFILLED';
export const POST_FILE_REJECTED = 'POST_FILE_REJECTED';

export const GET_DIR_TREE = 'GET_DIR_TREE';
export const GET_DIR_TREE_FULFILLED = 'GET_DIR_TREE_FULFILLED';
export const GET_DIR_TREE_REJECTED = 'GET_DIR_TREE_REJECTED';